version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
       - NODE_ENV=development
       - PORT=8000
    env_file:
       - .env.development.local
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/v1"]
      interval: 30s
      timeout: 10s
      retries: 3